name: Build and publish artifacts

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

env:
    LIBWEBP_VER: 1.2.2

jobs:
    test:
        name: Build and test
        strategy:
            matrix:
                java: [ 8, 17 ]
                os: [ ubuntu-latest, windows-latest, macos-latest ]
        runs-on: ${{ matrix.os }}
        steps:
            -   uses: actions/checkout@v3
            
            -   name: Install libwebp (Ubuntu)
                if: runner.os == 'Linux'
                run: ./setup/libwebp-ubuntu.sh ${{ env.LIBWEBP_VER }}

            -   name: Install libwebp (Windows)
                if: runner.os == 'Windows'
                run: .\setup\libwebp-windows.ps1 ${{ env.LIBWEBP_VER }}

            -   name: Install libwebp (macOS)
                if: runner.os == 'macOS'
                run: ./setup/libwebp-macos.sh ${{ env.LIBWEBP_VER }}
            
            -   uses: actions/setup-java@v2
                with:
                    distribution: 'temurin'
                    java-version: ${{ matrix.java }}
            
            -   name: Build Gradle
                uses: gradle/gradle-build-action@v2
                with:
                    arguments: build
            
            -   uses: actions/upload-artifact@v3.0.0
                with:
                    name: libwebp-${{ matrix.os }}
                    path: build/libs/*.jar
    
    publish:
        name: Publish artifacts
        if: github.event_name == 'push'
        strategy:
            matrix:
                os: [ ubuntu-latest, windows-latest, macos-latest ]
        runs-on: ${{ matrix.os }}
        needs: test
        steps:
            -   uses: actions/checkout@v3

            -   name: Install libwebp (Ubuntu)
                if: runner.os == 'Linux'
                run: ./setup/libwebp-ubuntu.sh ${{ env.LIBWEBP_VER }}

            -   name: Install libwebp (Windows)
                if: runner.os == 'Windows'
                run: .\setup\libwebp-windows.ps1 ${{ env.LIBWEBP_VER }}

            -   name: Install libwebp (macOS)
                if: runner.os == 'macOS'
                run: ./setup/libwebp-macos.sh ${{ env.LIBWEBP_VER }}
        
            -   uses: actions/setup-java@v2
                with:
                    distribution: 'temurin'
                    java-version: '17'
        
            -   name: Publish
                uses: gradle/gradle-build-action@v2
                continue-on-error: true
                with:
                    arguments: publish
                env:
                    GITHUB_ACTOR: ${{ github.actor }}
                    GITHUB_TOKEN: ${{ github.token }}
