name: Build artifacts

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  LIBWEBP_VER: 1.2.2
  LIBWEBP_DIR: libwebp

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: sudo apt install libjpeg-dev libpng-dev libtiff-dev libgif-dev
      
    - name: Download libwebp
      uses: actions/checkout@v3
      with:
        repository: 'https://chromium.googlesource.com/webm/libwebp'
        ref: v$LIBWEBP_VER
        path: $LIBWEBP_DIR
      
    - name: Configure libwebp
      working-directory: $LIBWEBP_DIR
      run: ./configure
      
    - name: Make libwebp
      working-directory: $LIBWEBP_DIR
      run: make
      
    - name: Install libwebp
      working-directory: $LIBWEBP_DIR
      run: sudo make install
      
    - uses: actions/checkout@v3
      
    - uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'
      
    - name: make
      run: make
      
    - uses: actions/upload-artifact@v3.0.0
      with:
        name: build/*.jar
  
  build-mac:
    runs-on: macos-latest
    steps:
    - name: Install libwebp
      run: brew install webp@$LIBWEBP_VER
    
    - uses: actions/checkout@v3
      
    - uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: make
      run: make
      
    - uses: actions/upload-artifact@v3.0.0
      with:
        name: build/*.jar
